interface Example {
    static readonly attribute unsigned long StaticReadOnly;

    static void StaticMethod();

  
};


enum Fruit2 {
    "Fruit::eAPPLE",
    "Fruit::eBANANA"
};

enum Fruit {
    "Apple",
    "Banana"
};


interface PxGeometry
{
    void getType();
};

interface PxHeightFieldGeometry
{
    boolean isValid();
};
PxHeightFieldGeometry implements PxGeometry;

interface PxRigidActor
{
};

// Brok
interface PxRigidStatic{
};
PxRigidStatic implements PxRigidActor;